default: &default
  adapter: <%= ENV['DATABASE_ADAPTER']%>
  database: <%= ENV['DATABASE_NAME']%>
  host: <%= ENV['DATABASE_HOST']%>
  username: <%= ENV['DATABASE_USERNAME']%>
  password: <%= ENV['DATABASE_PASSWORD']%>
  timeout: 5000

production:
  <<: *default
  pool: <%= ENV['DATABASE_POOL']%>

development:
  <<: *default
  pool: 5
